### PR TITLE
Add go-kit logger shim

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Did you have any chance to review this PR?

**Comment by sagikazarmark** [comment]
Ping :)

**Comment by talpert** [comment]
@sagikazarmark sorry for the delay! We completely missed this 😢 
Thank you for the contribution!

**Comment by sagikazarmark** [comment]
No problem. Can you maybe tag a new release as well?

**Pull request merged**
